name: Python application

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: install build pre-dependencies
      run: |
        pip install build
    - name: build
      run: |
        python -m build src/openswebcad
    - uses: actions/upload-artifact@v4
      with:
        name: wheel
        path: src/openswebcad/dist/*.whl
    - name: install package
      run: |
        pip install src/openswebcad/dist/*.whl
    - name: install test dependencies
      run: |
        pip install pytest pytest-asyncio
        apt-get install openscad
    - name: build
      run: |
        pytest src/openswebcad/tests
